name       : chiaki
version    : 2.1.1
release    : 7
source     :
    - git|https://git.sr.ht/~thestr4ng3r/chiaki : v2.1.1
license    : AGPL-3.0-only
component  : games
summary    : Free and Open Source PS4 Remote Play Client
description: |
    Chiaki is a Free and Open Source Software Client for PlayStation 4 Remote Play for Linux, macOS, Windows and potentially even more platforms.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(libavcodec)
    - pkgconfig(libevdev)
    - pkgconfig(libopusenc)
    - pkgconfig(libprotobuf-c)
    - pkgconfig(sdl2)
    - python-protobuf
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
