name       : chiaki
version    : 1.3.0
release    : 5
source     :
    - git|https://github.com/thestr4ng3r/chiaki.git : v1.3.0
license    : GPL-3.0-or-later
component  : games
summary    : Free and Open Source PS4 Remote Play Client
description: |
    Chiaki is a Free and Open Source Software Client for PlayStation 4 Remote Play for Linux, macOS, Windows and potentially even more platforms.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(libavcodec)
    - pkgconfig(libopusenc)
    - pkgconfig(libprotobuf-c)
    - pkgconfig(sdl2)
    - python-protobuf
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
